apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./generated/argo-cd/templates/argocd-notifications/rolebinding.yaml
- ./generated/argo-cd/templates/argocd-notifications/deployment.yaml
- ./generated/argo-cd/templates/argocd-notifications/clusterrolebinding.yaml
- ./generated/argo-cd/templates/argocd-notifications/role.yaml
- ./generated/argo-cd/templates/argocd-notifications/serviceaccount.yaml
- ./generated/argo-cd/templates/argocd-notifications/clusterrole.yaml
- ./generated/argo-cd/templates/dex/rolebinding.yaml
- ./generated/argo-cd/templates/dex/deployment.yaml
- ./generated/argo-cd/templates/dex/role.yaml
- ./generated/argo-cd/templates/dex/serviceaccount.yaml
- ./generated/argo-cd/templates/dex/service.yaml
- ./generated/argo-cd/templates/argocd-application-controller/rolebinding.yaml
- ./generated/argo-cd/templates/argocd-application-controller/clusterrolebinding.yaml
- ./generated/argo-cd/templates/argocd-application-controller/statefulset.yaml
- ./generated/argo-cd/templates/argocd-application-controller/role.yaml
- ./generated/argo-cd/templates/argocd-application-controller/serviceaccount.yaml
- ./generated/argo-cd/templates/argocd-application-controller/clusterrole.yaml
- ./generated/argo-cd/templates/redis-secret-init/rolebinding.yaml
- ./generated/argo-cd/templates/redis-secret-init/job.yaml
- ./generated/argo-cd/templates/redis-secret-init/role.yaml
- ./generated/argo-cd/templates/redis-secret-init/serviceaccount.yaml
- ./generated/argo-cd/templates/argocd-applicationset/rolebinding.yaml
- ./generated/argo-cd/templates/argocd-applicationset/deployment.yaml
- ./generated/argo-cd/templates/argocd-applicationset/role.yaml
- ./generated/argo-cd/templates/argocd-applicationset/serviceaccount.yaml
- ./generated/argo-cd/templates/argocd-applicationset/service.yaml
- ./generated/argo-cd/templates/argocd-repo-server/rolebinding.yaml
- ./generated/argo-cd/templates/argocd-repo-server/deployment.yaml
- ./generated/argo-cd/templates/argocd-repo-server/role.yaml
- ./generated/argo-cd/templates/argocd-repo-server/hpa.yaml
- ./generated/argo-cd/templates/argocd-repo-server/serviceaccount.yaml
- ./generated/argo-cd/templates/argocd-repo-server/service.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-notifications-secret.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-notifications-cm.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-rbac-cm.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-ssh-known-hosts-cm.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-secret.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-tls-certs-cm.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-cmd-params-cm.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-cm.yaml
- ./generated/argo-cd/templates/argocd-configs/argocd-gpg-keys-cm.yaml
- ./generated/argo-cd/templates/redis/deployment.yaml
- ./generated/argo-cd/templates/redis/service.yaml
- ./generated/argo-cd/templates/redis/health-configmap.yaml
- ./generated/argo-cd/templates/argocd-server/rolebinding.yaml
- ./generated/argo-cd/templates/argocd-server/deployment.yaml
- ./generated/argo-cd/templates/argocd-server/clusterrolebinding.yaml
- ./generated/argo-cd/templates/argocd-server/role.yaml
- ./generated/argo-cd/templates/argocd-server/ingress.yaml
- ./generated/argo-cd/templates/argocd-server/serviceaccount.yaml
- ./generated/argo-cd/templates/argocd-server/clusterrole.yaml
- ./generated/argo-cd/templates/argocd-server/service.yaml
