global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "nfs-client"

auth:
  adminUser: admin
  adminPassword: "Admin!23"

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.mgmt.cloud.com
  tls: true
  extraTls:
  - hosts:
    - keycloak.mgmt.cloud.com
    secretName: mgmt-tls
postgresql:
  enabled: true
  auth:
    postgresPassword: "test"
    username: bn_keycloak
    password: "test"
    database: bitnami_keycloak
    existingSecret: ""
  architecture: standalone
