apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
resources:
- ../../base

patches:
  - target:
      kind: Ingress
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "argo-cd.mgmt.cloud.com"
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "argo-cd.mgmt.cloud.com"
      - op: replace
        path: /spec/tls/0/secretName
        value: "wildcard-tls"
