apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mgmt-monitoring-prj
  namespace: argo-cd
spec:
  sourceRepos:
    - 'https://github.com/woojuhee/gitops'
  destinations:
    - namespace: mgmt-monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
