apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mgmt-dev-prj
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/woojuhee/gitops'
  destinations:
    - namespace: mgmt-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
