apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: palworld-prj
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/woojuhee/gitops'
  destinations:
    - namespace: palworld
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
