controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  # tag: "2.414.2-jdk11"
  tagLabel: jdk11
  imagePullPolicy: "IfNotPresent"
  adminSecret: true
  adminUser: "admin"
  adminPassword: "Admin!23"
  installPlugins:
    - kubernetes:4029.v5712230ccb_f8
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.1.0
    - configuration-as-code:1670.v564dc8b_982d0
  installLatestPlugins: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.mgmt.cloud.com
agent:
  enabled: true
  jenkinsUrl: jenkins.mgmt.cloud.com
  namespace: mgmt-dev
  image: "jenkins/inbound-agent"
  tag: "3107.v665000b_51092-15"
  podName: "default"
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: agent
        image: jenkins/jnlp-agent-docker
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        command:
        - cat
        tty: true
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
  additionalContainers:
    - sideContainerName: dind
      image: docker
      tag: dind
      command: dockerd-entrypoint.sh
      args: ""
      tty: true
persistence:
  enabled: true
  existingClaim:
  storageClass: nfs-client
  annotations: {}
  labels: {}
  accessMode: "ReadWriteMany"
  size: "8Gi"
