controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  # tag: "2.414.2-jdk11"
  tagLabel: jdk11
  imagePullPolicy: "IfNotPresent"
  adminSecret: true
  adminUser: "admin"
  adminPassword: "Admin!23"
  installPlugins:
    - kubernetes:4029.v5712230ccb_f8
    - workflow-aggregator:596.v8c21c963d92d
    - git:5.1.0
    - configuration-as-code:1670.v564dc8b_982d0
  installLatestPlugins: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.mgmt.cloud.com
persistence:
  enabled: true
  existingClaim:
  storageClass: nfs-client
  annotations: {}
  labels: {}
  accessMode: "ReadWriteMany"
  size: "8Gi"
