---
# Source: mariadb-galera/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-mariadb-galera
  namespace: "dev"
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-9.0.5
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "cm9vdA=="
  mariadb-password: "dGh3U2ZGSXg3bw=="
  mariadb-galera-mariabackup-password: "clZzYUZlU1J6Mw=="
