apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-petclinic-configmap
data:
  application.properties: |
    # database init
    spring.datasource.url=jdbc:mysql://${MYSQL_HOSTNAME}
    spring.datasource.username=${MYSQL_USERNAME}
    spring.datasource.password=${MYSQL_PASSWORD}

    # do not attempt to replace database with in-memory database
    spring.test.database.replace=none

    # Internationalization
    spring.messages.basename=messages/messages

    # Actuator / Management
    management.endpoints.web.base-path=/manage
    management.endpoints.web.exposure.include=*

    # Logging
    logging.level.org.springframework=debug
    logging.level.sql=debug
    # logging.level.org.springframework.web=debug
    # logging.level.org.springframework.context.annotation=trace
    logging.file.path=/logs

    # Maximum time static resources should be cached
    spring.web.resources.cache.cachecontrol.max-age=12h
