apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mgmt-dev  # Set the namespace
resources:
- ../../base
images:
  - name: jheewoo/spring-petclinic-data-jdbc
    newTag: dev-12-gdb41807-gradle
