global:
  imageRegistry: harbor.jerry.com
  storageClass: nfs-csi

image:
  debug: true
  repository: docker-devops/mariadb-galera
  tag: 11.0.3-debian-11-r7-1

rootUser:
  password: root

replicaCount: 3

persistence:
  enabled: true
