---
# Source: minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: "mgmt-dev"
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.7.15
    helm.sh/chart: minio-14.6.22
type: Opaque
data:
  root-user: "YWRtaW4="
  root-password: "QWRtaW4hMjM="
