apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-datta-able-application
  namespace: argo-cd
spec:
  project: mgmt-dev-prj
  source:
    repoURL: https://github.com/woojuhee/gitops.git
    targetRevision: master
    path: gitops/mgmt/flask-datta-able/kustomize/overlays/mgmt-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mgmt-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - SkipDryRunOnMissingResource=true
    - ApplyOutOfSyncOnly=true
