apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-client-application
  namespace: argocd
spec:
  project: mgmt-dev-prj
  source:
    repoURL: https://github.com/woojuhee/gitops.git
    targetRevision: master
    path: gitops/mgmt/nfs-provisioner/
  destination:
    server: https://192.168.45.201:6443
    namespace: mgmt-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
