apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
#- ./application/kube-prometheus-stack-48.3.3-application.yaml
- ./application/kube-prometheus-stack-56.6.1-application.yaml
