apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: palworld
resources:
- ../../base

images:
- name: thijsvanloef/palworld-server-docker
  newTag: dev

patches:
  - target:
      kind: Deployment
      name: palworld-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "20Gi"
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          kubernetes.io/steam: "yes"
  - target:
      kind: CronJob
      name: restart-deployment
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "30 */3 * * *"
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 3
